create table if not exists student (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	active_course INT,
	certificate_earned INT,
	course_enrolled INT,
	hours_watched INT,
	country VARCHAR(50),
	sex VARCHAR(50),
	date_of_birth DATE,
	schedules INT,
	email_address VARCHAR(50),
	profile_picture VARCHAR(50)
);
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (1, 'Eleanor', 'Ivanenko', 10, 140, 97, 448, 'Uganda', 'Female', '9/23/1982', 23, 'eivanenko0@desdev.cn', 'http://dummyimage.com/128x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (2, 'Prince', 'Cottisford', 355, 229, 309, 461, 'Sri Lanka', 'Male', '9/13/1996', 27, 'pcottisford1@marriott.com', 'http://dummyimage.com/173x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (3, 'Anneliese', 'Hince', 128, 403, 399, 517, 'Portugal', 'Female', '1/13/1991', 30, 'ahince2@craigslist.org', 'http://dummyimage.com/186x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (4, 'Saunderson', 'McGlynn', 445, 304, 240, 13, 'Indonesia', 'Male', '1/17/1994', 43, 'smcglynn3@digg.com', 'http://dummyimage.com/151x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (5, 'Muire', 'Delaney', 413, 438, 108, 209, 'Ireland', 'Female', '2/4/1985', 38, 'mdelaney4@youtu.be', 'http://dummyimage.com/221x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (6, 'Lindsey', 'Lehrmann', 53, 285, 519, 28, 'Norway', 'Female', '3/28/1988', 22, 'llehrmann5@drupal.org', 'http://dummyimage.com/209x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (7, 'Forbes', 'Shotboult', 137, 292, 396, 287, 'Poland', 'Male', '4/12/1980', 6, 'fshotboult6@aol.com', 'http://dummyimage.com/205x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (8, 'Gerick', 'Petrelluzzi', 82, 316, 561, 559, 'United States', 'Male', '1/25/1972', 24, 'gpetrelluzzi7@deliciousdays.com', 'http://dummyimage.com/208x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (9, 'Tades', 'Dugan', 453, 422, 448, 222, 'China', 'Male', '4/9/2001', 33, 'tdugan8@google.cn', 'http://dummyimage.com/118x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (10, 'Gonzales', 'Florence', 156, 485, 194, 389, 'Indonesia', 'Male', '5/12/1995', 35, 'gflorence9@vimeo.com', 'http://dummyimage.com/224x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (11, 'Barton', 'Jagg', 367, 540, 220, 420, 'Croatia', 'Male', '6/9/1985', 40, 'bjagga@indiatimes.com', 'http://dummyimage.com/107x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (12, 'Sawyer', 'Attwool', 317, 9, 542, 255, 'China', 'Male', '7/4/1976', 44, 'sattwoolb@nps.gov', 'http://dummyimage.com/227x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (13, 'Cori', 'Barnardo', 399, 15, 573, 379, 'United States', 'Female', '9/27/1997', 19, 'cbarnardoc@cdbaby.com', 'http://dummyimage.com/196x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (14, 'Whitby', 'Tuer', 352, 490, 533, 275, 'Indonesia', 'Male', '8/1/1964', 3, 'wtuerd@cocolog-nifty.com', 'http://dummyimage.com/112x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (15, 'Hieronymus', 'Apfel', 250, 374, 545, 407, 'Canada', 'Male', '6/21/1970', 9, 'hapfele@newsvine.com', 'http://dummyimage.com/133x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (16, 'Dane', 'Ashwin', 116, 462, 165, 230, 'Dominican Republic', 'Male', '11/10/2002', 9, 'dashwinf@google.ru', 'http://dummyimage.com/198x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (17, 'Brien', 'Knell', 320, 426, 309, 362, 'Uzbekistan', 'Male', '5/27/1984', 45, 'bknellg@va.gov', 'http://dummyimage.com/242x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (18, 'Junia', 'Medler', 364, 204, 514, 396, 'Uganda', 'Female', '3/28/1985', 15, 'jmedlerh@artisteer.com', 'http://dummyimage.com/149x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (19, 'Consuela', 'Pringley', 212, 340, 78, 468, 'Mozambique', 'Female', '7/13/1994', 30, 'cpringleyi@army.mil', 'http://dummyimage.com/231x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (20, 'Rodger', 'Codi', 62, 484, 555, 334, 'Poland', 'Male', '11/18/1961', 25, 'rcodij@ibm.com', 'http://dummyimage.com/115x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (21, 'Alvis', 'Larcier', 238, 356, 269, 57, 'Argentina', 'Male', '3/20/1974', 27, 'alarcierk@bravesites.com', 'http://dummyimage.com/173x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (22, 'Roxane', 'Fildery', 19, 237, 551, 155, 'Croatia', 'Female', '8/5/1997', 36, 'rfilderyl@icio.us', 'http://dummyimage.com/146x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (23, 'Stillman', 'Norvel', 417, 421, 342, 112, 'Indonesia', 'Male', '8/16/1961', 36, 'snorvelm@slashdot.org', 'http://dummyimage.com/237x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (24, 'Polly', 'Epelett', 464, 524, 221, 418, 'United States', 'Female', '9/19/1975', 16, 'pepelettn@telegraph.co.uk', 'http://dummyimage.com/195x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (25, 'Rosy', 'Palfreman', 20, 497, 508, 63, 'China', 'Female', '1/7/1966', 20, 'rpalfremano@qq.com', 'http://dummyimage.com/136x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (26, 'Angie', 'Scotti', 14, 141, 537, 319, 'Colombia', 'Male', '12/30/1991', 6, 'ascottip@epa.gov', 'http://dummyimage.com/142x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (27, 'Adrien', 'Sturdy', 452, 76, 410, 272, 'Indonesia', 'Male', '10/7/1974', 35, 'asturdyq@dedecms.com', 'http://dummyimage.com/179x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (28, 'Samaria', 'Houson', 122, 367, 283, 169, 'Philippines', 'Female', '3/20/1961', 14, 'shousonr@hugedomains.com', 'http://dummyimage.com/119x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (29, 'Pamelina', 'Rimington', 32, 257, 491, 382, 'Ukraine', 'Female', '12/22/1974', 32, 'primingtons@miibeian.gov.cn', 'http://dummyimage.com/179x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (30, 'Norma', 'Querrard', 483, 303, 152, 594, 'Guyana', 'Female', '8/18/1981', 45, 'nquerrardt@desdev.cn', 'http://dummyimage.com/173x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (31, 'Ketty', 'Lasselle', 435, 517, 568, 425, 'China', 'Female', '7/9/1997', 46, 'klasselleu@harvard.edu', 'http://dummyimage.com/195x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (32, 'Vanya', 'Harmes', 140, 306, 43, 252, 'China', 'Male', '5/8/1998', 32, 'vharmesv@shop-pro.jp', 'http://dummyimage.com/172x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (33, 'Coral', 'Poone', 472, 169, 57, 378, 'China', 'Female', '3/1/2002', 46, 'cpoonew@yahoo.co.jp', 'http://dummyimage.com/113x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (34, 'Ginger', 'Willshaw', 122, 210, 378, 104, 'China', 'Male', '6/14/1973', 36, 'gwillshawx@angelfire.com', 'http://dummyimage.com/106x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (35, 'Beitris', 'Bispham', 66, 528, 361, 374, 'Russia', 'Female', '10/5/2004', 34, 'bbisphamy@utexas.edu', 'http://dummyimage.com/244x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (36, 'Marrissa', 'Harvett', 307, 495, 164, 528, 'Mexico', 'Female', '8/25/2000', 11, 'mharvettz@storify.com', 'http://dummyimage.com/131x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (37, 'Janek', 'Arnall', 273, 261, 491, 154, 'Indonesia', 'Male', '11/2/1997', 42, 'jarnall10@1und1.de', 'http://dummyimage.com/217x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (38, 'Gunar', 'Gentil', 19, 63, 355, 150, 'Czech Republic', 'Male', '2/27/1990', 7, 'ggentil11@huffingtonpost.com', 'http://dummyimage.com/250x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (39, 'Lucius', 'Swane', 500, 103, 129, 585, 'Poland', 'Male', '1/20/1994', 16, 'lswane12@cbsnews.com', 'http://dummyimage.com/226x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (40, 'Gustavo', 'Spaven', 38, 406, 245, 226, 'United States', 'Male', '2/15/1989', 4, 'gspaven13@dailymail.co.uk', 'http://dummyimage.com/108x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (41, 'Coralyn', 'Shoubridge', 148, 302, 555, 4, 'China', 'Female', '8/23/1966', 14, 'cshoubridge14@w3.org', 'http://dummyimage.com/172x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (42, 'Sinclare', 'Rignoldes', 332, 134, 590, 425, 'Vietnam', 'Male', '9/2/1977', 21, 'srignoldes15@oakley.com', 'http://dummyimage.com/224x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (43, 'Manya', 'Wooff', 432, 434, 476, 438, 'Japan', 'Female', '10/8/2001', 36, 'mwooff16@ucoz.com', 'http://dummyimage.com/220x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (44, 'Natalina', 'Smetoun', 182, 450, 570, 64, 'China', 'Female', '2/2/1982', 21, 'nsmetoun17@163.com', 'http://dummyimage.com/238x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (45, 'Teddi', 'Scouller', 174, 69, 537, 501, 'Brazil', 'Female', '10/23/1985', 6, 'tscouller18@newsvine.com', 'http://dummyimage.com/199x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (46, 'Sam', 'Balnaves', 406, 496, 598, 308, 'Afghanistan', 'Male', '12/1/1997', 45, 'sbalnaves19@utexas.edu', 'http://dummyimage.com/146x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (47, 'Jeannette', 'Batchelar', 363, 549, 186, 39, 'China', 'Female', '9/2/2002', 22, 'jbatchelar1a@diigo.com', 'http://dummyimage.com/165x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (48, 'Wendall', 'Pull', 327, 17, 499, 580, 'Colombia', 'Male', '4/14/1993', 23, 'wpull1b@amazon.co.jp', 'http://dummyimage.com/129x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (49, 'Dall', 'Ortega', 2, 537, 366, 275, 'Indonesia', 'Male', '11/23/1999', 32, 'dortega1c@feedburner.com', 'http://dummyimage.com/122x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (50, 'Justino', 'Guwer', 428, 156, 419, 176, 'Mali', 'Male', '1/9/1986', 40, 'jguwer1d@joomla.org', 'http://dummyimage.com/224x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (51, 'Nissa', 'Annott', 426, 181, 233, 78, 'Brazil', 'Female', '5/29/1976', 12, 'nannott1e@gnu.org', 'http://dummyimage.com/104x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (52, 'Clint', 'McGucken', 272, 404, 443, 133, 'France', 'Male', '6/20/1983', 10, 'cmcgucken1f@paginegialle.it', 'http://dummyimage.com/227x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (53, 'Burnard', 'Sneesby', 231, 248, 65, 18, 'China', 'Male', '2/22/1994', 17, 'bsneesby1g@simplemachines.org', 'http://dummyimage.com/197x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (54, 'Vite', 'Zapata', 332, 298, 124, 217, 'Philippines', 'Male', '3/13/2000', 9, 'vzapata1h@webeden.co.uk', 'http://dummyimage.com/247x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (55, 'Fax', 'Patman', 410, 317, 562, 14, 'Ukraine', 'Male', '12/10/1963', 22, 'fpatman1i@disqus.com', 'http://dummyimage.com/189x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (56, 'Joletta', 'Norres', 72, 584, 83, 91, 'Russia', 'Female', '8/16/1979', 40, 'jnorres1j@sohu.com', 'http://dummyimage.com/118x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (57, 'Abbey', 'Di Biasi', 355, 427, 217, 591, 'Finland', 'Male', '5/7/1988', 7, 'adibiasi1k@un.org', 'http://dummyimage.com/221x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (58, 'Hilario', 'Dauber', 409, 352, 240, 492, 'China', 'Male', '12/31/1999', 41, 'hdauber1l@paypal.com', 'http://dummyimage.com/218x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (59, 'Antonie', 'Durrad', 286, 50, 376, 168, 'Indonesia', 'Female', '5/31/1971', 21, 'adurrad1m@ow.ly', 'http://dummyimage.com/152x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (60, 'Petronella', 'Snassell', 210, 368, 190, 35, 'Russia', 'Female', '6/4/1994', 24, 'psnassell1n@adobe.com', 'http://dummyimage.com/101x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (61, 'Bancroft', 'Murford', 284, 215, 271, 32, 'China', 'Male', '8/4/1980', 1, 'bmurford1o@apache.org', 'http://dummyimage.com/158x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (62, 'Karen', 'Larrosa', 62, 93, 427, 203, 'Sweden', 'Female', '8/15/1989', 23, 'klarrosa1p@cloudflare.com', 'http://dummyimage.com/249x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (63, 'Constantin', 'Gostall', 55, 71, 146, 291, 'Greece', 'Male', '1/14/1962', 38, 'cgostall1q@sfgate.com', 'http://dummyimage.com/232x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (64, 'Ignace', 'Sucre', 138, 261, 36, 580, 'Serbia', 'Male', '8/12/1972', 22, 'isucre1r@mapy.cz', 'http://dummyimage.com/242x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (65, 'Emmey', 'Seakings', 397, 384, 167, 437, 'Morocco', 'Female', '4/7/1979', 10, 'eseakings1s@gmpg.org', 'http://dummyimage.com/127x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (66, 'Alano', 'Gisburn', 123, 84, 295, 301, 'Sweden', 'Male', '1/5/1999', 37, 'agisburn1t@deviantart.com', 'http://dummyimage.com/188x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (67, 'Scarlett', 'Tattershaw', 458, 521, 428, 356, 'China', 'Female', '8/19/1995', 15, 'stattershaw1u@free.fr', 'http://dummyimage.com/153x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (68, 'Remus', 'Korlat', 6, 441, 470, 537, 'France', 'Male', '5/14/1993', 17, 'rkorlat1v@com.com', 'http://dummyimage.com/207x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (69, 'Free', 'Micheu', 457, 408, 138, 528, 'Paraguay', 'Male', '4/6/1977', 13, 'fmicheu1w@list-manage.com', 'http://dummyimage.com/171x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (70, 'Chrissie', 'Slaney', 312, 96, 383, 122, 'Ukraine', 'Male', '2/3/1978', 48, 'cslaney1x@dmoz.org', 'http://dummyimage.com/224x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (71, 'Kissee', 'Dunbleton', 170, 572, 440, 150, 'Philippines', 'Female', '6/23/1988', 26, 'kdunbleton1y@mlb.com', 'http://dummyimage.com/164x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (72, 'Tanya', 'Saunders', 177, 54, 383, 424, 'Zambia', 'Female', '10/14/1980', 2, 'tsaunders1z@csmonitor.com', 'http://dummyimage.com/217x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (73, 'Pam', 'Bilston', 33, 65, 331, 550, 'Sweden', 'Female', '10/20/1989', 44, 'pbilston20@disqus.com', 'http://dummyimage.com/175x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (74, 'Clywd', 'Bilyard', 149, 513, 256, 273, 'Portugal', 'Male', '5/24/1989', 44, 'cbilyard21@nhs.uk', 'http://dummyimage.com/123x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (75, 'Christel', 'Serjeant', 101, 468, 509, 59, 'China', 'Female', '8/16/1995', 28, 'cserjeant22@businessweek.com', 'http://dummyimage.com/194x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (76, 'Shawn', 'Attwooll', 375, 177, 276, 517, 'Paraguay', 'Male', '10/15/2004', 16, 'sattwooll23@goo.ne.jp', 'http://dummyimage.com/101x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (77, 'Adolph', 'Cancellario', 322, 51, 137, 596, 'Argentina', 'Male', '6/29/2003', 47, 'acancellario24@photobucket.com', 'http://dummyimage.com/146x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (78, 'Tandi', 'Carriage', 39, 70, 371, 304, 'Indonesia', 'Female', '1/4/1972', 35, 'tcarriage25@rakuten.co.jp', 'http://dummyimage.com/230x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (79, 'Randall', 'Wallbutton', 370, 70, 481, 377, 'Indonesia', 'Male', '8/3/1993', 11, 'rwallbutton26@cbsnews.com', 'http://dummyimage.com/164x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (80, 'Rudolfo', 'Farmiloe', 273, 198, 599, 6, 'Peru', 'Male', '5/23/1997', 17, 'rfarmiloe27@guardian.co.uk', 'http://dummyimage.com/227x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (81, 'Coralie', 'Bendson', 164, 93, 284, 503, 'United States', 'Female', '2/14/2001', 29, 'cbendson28@bigcartel.com', 'http://dummyimage.com/141x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (82, 'Wilden', 'Bell', 393, 326, 451, 529, 'Indonesia', 'Male', '5/15/2002', 4, 'wbell29@auda.org.au', 'http://dummyimage.com/241x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (83, 'Delaney', 'Figgen', 134, 92, 230, 530, 'Portugal', 'Male', '12/31/1997', 32, 'dfiggen2a@scribd.com', 'http://dummyimage.com/111x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (84, 'Nora', 'Oliffe', 54, 294, 257, 537, 'Poland', 'Female', '11/16/1960', 40, 'noliffe2b@1688.com', 'http://dummyimage.com/127x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (85, 'Bartram', 'Tayspell', 323, 587, 62, 474, 'Philippines', 'Male', '10/11/1961', 43, 'btayspell2c@mediafire.com', 'http://dummyimage.com/200x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (86, 'Wilton', 'Savaage', 244, 586, 244, 293, 'Afghanistan', 'Male', '8/5/1964', 35, 'wsavaage2d@blinklist.com', 'http://dummyimage.com/208x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (87, 'Lazarus', 'Gowry', 232, 373, 31, 509, 'China', 'Male', '7/11/1979', 15, 'lgowry2e@hostgator.com', 'http://dummyimage.com/192x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (88, 'Cello', 'Ianniello', 407, 419, 417, 223, 'Russia', 'Male', '1/12/1983', 40, 'cianniello2f@indiatimes.com', 'http://dummyimage.com/114x100.png/5fa2dd/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (89, 'Ardra', 'Hacquel', 216, 424, 514, 411, 'France', 'Female', '8/19/1979', 43, 'ahacquel2g@istockphoto.com', 'http://dummyimage.com/234x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (90, 'Selina', 'Circuit', 284, 49, 134, 184, 'Mongolia', 'Female', '3/14/1977', 46, 'scircuit2h@uol.com.br', 'http://dummyimage.com/168x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (91, 'Tremain', 'Spillman', 447, 463, 232, 11, 'United States', 'Male', '5/14/1965', 48, 'tspillman2i@ning.com', 'http://dummyimage.com/145x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (92, 'Kath', 'Ashment', 41, 272, 511, 67, 'Venezuela', 'Female', '5/4/2001', 2, 'kashment2j@sakura.ne.jp', 'http://dummyimage.com/134x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (93, 'Orsa', 'Cogin', 176, 492, 471, 184, 'Nigeria', 'Female', '7/5/2001', 24, 'ocogin2k@surveymonkey.com', 'http://dummyimage.com/190x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (94, 'Sheryl', 'Deniseau', 52, 377, 76, 115, 'Canada', 'Female', '10/4/1973', 26, 'sdeniseau2l@kickstarter.com', 'http://dummyimage.com/202x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (95, 'Julita', 'Stelljes', 438, 273, 290, 46, 'China', 'Female', '4/30/1995', 21, 'jstelljes2m@apple.com', 'http://dummyimage.com/245x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (96, 'Torrey', 'Richemond', 424, 65, 68, 146, 'Guinea', 'Male', '6/17/1971', 4, 'trichemond2n@mac.com', 'http://dummyimage.com/148x100.png/cc0000/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (97, 'Eugenie', 'Southorn', 403, 107, 520, 113, 'Albania', 'Female', '4/16/1970', 34, 'esouthorn2o@gov.uk', 'http://dummyimage.com/167x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (98, 'Hillier', 'Bountiff', 77, 595, 365, 315, 'Indonesia', 'Male', '3/12/2001', 16, 'hbountiff2p@ovh.net', 'http://dummyimage.com/213x100.png/ff4444/ffffff');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (99, 'Gabriele', 'Johannesson', 394, 203, 336, 47, 'China', 'Male', '6/26/1988', 38, 'gjohannesson2q@java.com', 'http://dummyimage.com/198x100.png/dddddd/000000');
insert into user (id, first_name, last_name, active_course, certificate_earned, course_enrolled, hours_watched, country, sex, date_of_birth, schedules, email_address, profile_picture) values (100, 'Zacherie', 'O''Shea', 92, 479, 242, 532, 'Philippines', 'Male', '3/10/1962', 48, 'zoshea2r@utexas.edu', 'http://dummyimage.com/212x100.png/ff4444/ffffff');
